# -*- coding: utf-8 -*-
"""00_HelloWorld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xzs6rCKaK0SOoDxs7Fm2g3WUW-9hoU0x
"""

#este simbolo se utiliza para comentar.
print("Hola grupo 430 de la carrera tecnica de programacion")
#como consultar el tipo de dato
print(type("soy un dato str")) #tipo"str"
print(type(5)) #tipo"int"
print(type(1.5)) #tipo"float"
print(type(3 + 1j))  # tipo "complex"
print(type(True))  # tipo "bool"
print(type(print("mi cadena de texto")))  # tipo "NoneType"