# -*- coding: utf-8 -*-
"""08.Conditionals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mTOYlsqmQjA3wVSfdC5saPCu1kGUjU24
"""

###Conditionals###
#if
my_conditional =False
if my_conditional: #es lo mismo que if my_condition == True:
   print("Se ejecuta la condicion del if")
   my_condition= 5*5

my_conditional = 5*5
if my_conditional == 10:
   #es lo mismo que if my_condition == True:
   print("Se ejecuta la condicion del segundo if")

# if,elif,else

if my_condition> 10 and my_condition<20:
    print("Es mayor que 10 y menor que 20")
elif my_condition==25:
    print("Es igual a 25")
else:
    print("Es menor o igual que 10 o mayor o igual que a 20 o distinto de 25")

print("La ejecucion continua")


##Condition con valor##
my_string=""

if not my_string:#si esta vacio es falso y con el not camvia el valor
   print("Mi cadena de texto es vacia")
if my_string=="Mi cadena de textooooooo":
   print("Estas cadena de texto coinciden")