# -*- coding: utf-8 -*-
"""09_Loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x6drFU3b_vBTly5l0u120xYg627EhYM4
"""

### Loops ###
#while
my_condition = 0
while my_condition < 10:
    print(my_condition)
    my_condition += 1
else:  # Optional
    print("My condition is greater than or equal to 10")
    print("The execution continues")

while my_condition < 20:
    my_condition += 1
    if my_condition == 15:
        print("Execution stopped")
        break
    print(my_condition)
print("The execution continues")

# for

my_list = [35, 24, 62, 52, 30, 30, 18]

for element in my_list:
    print(element)

my_tuple = (16, 1.79, "luis", "Ramirez", "Hidalgo")

for element in my_tuple:
    print(element)

my_set = {"Luis", "Ramirez", "16"}
for element in my_set:
    print(element)

my_dict = {"Nombre": "luis", "Apellido": "Ramirez", "Edad": 35, 1: "Python"}

for element in my_dict:
    print(element)
    if element == "Edad":
        break
else:
    print("The for loop for dictionary has finished")

my_dict = {"Nombre": "luis", "Apellido": "Ramirez", "Edad": 35, 1: "Python"}

for element in my_dict:
    print(element)
    if element == "Edad":
        break
    else:
        print("The for loop for dictionary has finished")