# -*- coding: utf-8 -*-
"""11_Classes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10RYLxUGdHfKkc5e924dtQXzR5IC5cXYw
"""

###Classes ###
# Definition
class MyEmptyPerson:
  pass # To be able to leave the class empty

print(MyEmptyPerson)
print(MyEmptyPerson())

 #Class with constructor, functions and private and public properties

class Person:
   def __init__(self, name, surname, alias="Sin alias"):
     self.full_name = f"{name} {surname} ((alias))" # Public property
     self._name = name # Private property

   def get_name(self):
       return self._name

   def walk(self):
       print(f"{self.full_name} está caminando")


my_person = Person("Fermín", "García")

print(my_person.full_name)

print(my_person.get_name())
my_person.walk()

my_other_person = Person("Fermin", "García", "GarcíaDev")

print(my_other_person.full_name)

my_other_person.walk()

my_other_person.full_name = "Héctor de León"

print(my_other_person.full_name)

my_other_person.full_name = 666

print(my_other_person.full_name)